syntax = "proto3";

package user.v1;

option java_package = "org.example.grpc.user";
option java_multiple_files = true;
option java_outer_classname = "UserProto";

import "google/protobuf/timestamp.proto";

message GrpcUser {
  string sub = 1;
  string nickname = 2;
  string email = 3;
  repeated string roles = 4;
  google.protobuf.Timestamp created_at = 5;
  string id = 6;
}

message GrpcFindByEmailRequest {
  string email = 1;
}

message GrpcFindByEmailResponse {
  optional GrpcUser user = 1;
}

message GrpcSignUpOauth2Request {
  string sub = 1;
  string email = 2;
  string nickname = 3;
}

message GrpcSignUpOauth2Response {
  GrpcUser user = 1;
}

service UserService {
  rpc FindByEmail(GrpcFindByEmailRequest) returns (GrpcFindByEmailResponse);
  rpc SignUpOauth2(GrpcSignUpOauth2Request) returns (GrpcSignUpOauth2Response);
}
