syntax = "proto3";

package user.v1;

option java_package = "org.example.grpc.user";
option java_multiple_files = true;
option java_outer_classname = "UserProto";

import "google/protobuf/timestamp.proto";

message UserGrpc {
  string sub = 1;
  string nickname = 2;
  string email = 3;
  repeated string roles = 4;
  google.protobuf.Timestamp created_at = 5;
  string id = 6;
}

message FindByEmailGrpcRequest {
  string email = 1;
}

message FindByEmailGrpcResponse {
  optional UserGrpc user = 1;
}

message SignUpOauth2GrpcRequest {
  string sub = 1;
  string email = 2;
  string nickname = 3;
}

message SignUpOauth2GrpcResponse {
  UserGrpc user = 1;
}

service UserService {
  rpc FindByEmail(FindByEmailGrpcRequest) returns (FindByEmailGrpcResponse);
  rpc SignUpOauth2(SignUpOauth2GrpcRequest) returns (SignUpOauth2GrpcResponse);
}
