plugins {
    id 'crypto-adapter'
}


dependencies {
    api project(':common:common-web')
    api project(':common:common-grpc')
    api project(':chat:chat-application')
    api project(':protobuf')

    api platform(libs.grpc.bom)
    api(libs.grpc.stub)
    api(libs.grpc.server.spring.boot.starter)
    api(libs.spring.boot.starter.web)
    api(libs.spring.boot.starter.validation)
    api(libs.spring.cloud.starter.stream.kafka)
    implementation(libs.spring.integration.core)

    testImplementation project(':chat:chat-adapter-out')
    testImplementation project(':common:common-test')
}
