plugins {
    id 'crypto-adapter'
}


dependencies {
    implementation project(':common:common-web')
    implementation project(':common:common-grpc')
    implementation project(':chat:chat-application')
    implementation project(':protobuf')

    implementation platform(libs.grpc.bom)
    implementation(libs.grpc.stub)
    implementation(libs.grpc.server.spring.boot.starter)
    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.spring.cloud.starter.stream.kafka)
    implementation(libs.spring.integration.core)

    testImplementation project(':chat:chat-adapter-out')
    testImplementation project(':common:common-test')
}