plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-exception')
    implementation project(':common:common-validation')
    implementation project(':common:common-web')
    implementation project(':common:common-outbox')
    implementation project(':common:common-grpc-server')
    implementation project(':protobuf')
    implementation project(':chat:chat-application')
    implementation(libs.grpc.server.spring.boot.starter)
    implementation(libs.spring.cloud.starter.stream.kafka)

    testImplementation project(':common:common-test')
    testImplementation project(':chat:chat-adapter-out')
    testImplementation(libs.mongodb.bson)
}
