plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-spring-cloud-api-gateway"

dependencies {
    implementation project(':common:common-core')
    implementation project(':common:common-actuator-webmvc')
    implementation project(':protobuf')
    implementation project(':oauth2-authorization-server:oauth2-authorization-server-client')

    implementation(platform(libs.grpc.bom))
    implementation(libs.grpc.netty)
    implementation(libs.grpc.protobuf)
    implementation(libs.grpc.stub)
    implementation(libs.grpc.client.spring.boot.starter)

    implementation(libs.protobuf.java)
    implementation(libs.protobuf.util)

    implementation(libs.spring.boot.starter.webflux)
    implementation(libs.spring.boot.starter.security)
    implementation(libs.spring.security.oauth2.jose)
    implementation(libs.spring.security.oauth2.resource.server)

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)
    implementation(libs.spring.cloud.gateway)
    implementation(libs.spring.cloud.loadbalancer)

    testImplementation project(':common:common-test')
    testImplementation(libs.spring.security.test)
    testImplementation(libs.reactor.test)
}