plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-chat-service"

dependencies {
    runtimeOnly(libs.mysql.connector.j) {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
    }

    implementation project(':chat:chat-domain')
    implementation project(':chat:chat-application')
    implementation project(':chat:chat-adapter-in')
    implementation project(':chat:chat-adapter-out')

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)

    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.micrometer.registry.prometheus)
}