plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-validation')
    implementation project(':common:common-time')
    implementation project(':common:common-core')
    implementation project(':common:common-grpc-client')
    implementation project(':common:common-id')
    implementation project(':common:common-jpa')
    implementation project(':common:common-mongo')
    implementation project(':common:common-redis')
    implementation project(':market:market-client')
    implementation project(':notification:notification-application')

    testImplementation project(':common:common-test')
}
