plugins {
    id 'crypto-common-library'
}

dependencies {
    runtimeOnly(libs.mysql.connector.j) {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
    }

    api(libs.spring.boot.starter.data.jpa)
    api(libs.spring.boot.starter.aop)

    testImplementation project(':common:common-test')
    testRuntimeOnly libs.mysql.connector.j
}
