plugins {
    id 'crypto-application'
}


dependencies {
    implementation project(':common:common-core')
    api project(':user:user-contract')

    implementation(libs.spring.boot.starter.oauth2.client)
    implementation(libs.spring.boot.starter.web)

    testImplementation(libs.spring.security.test)
    testImplementation project(':common:common-test')
}