plugins {
    id 'crypto-application'
}

dependencies {
    api project(':common:common-core')
    api project(':user:user-contract')
    api(libs.spring.boot.starter.web)
    api(libs.spring.boot.starter.oauth2.client)

    implementation project(':common:common-exception')

    testImplementation(libs.spring.security.test)
    testImplementation project(':common:common-test')
}