plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-core')
    implementation project(':common:common-outbox')

    runtimeOnly libs.mysql.connector.j

    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.cloud.starter.stream.kafka
    implementation libs.spring.cloud.stream.binder.kafka
}