plugins {
    id 'crypto-application'
}


dependencies {
    implementation project(':common:common-core')

    implementation(libs.spring.security.oauth2.jose)
    implementation(libs.spring.security.oauth2.resource.server)
    implementation(libs.spring.boot.starter.security)

    testImplementation(libs.spring.security.test)
}