plugins {
    id 'crypto-adapter'
}

dependencies {
    compileOnly (libs.spring.boot.actuator.autoconfigure)

    implementation project(':common:common-core')
    implementation project(':common:common-id')
    implementation project(':common:common-redis')
    implementation project(':websocket-gateway:websocket-gateway-application')
    implementation project(':chat:chat-client')

    implementation(libs.spring.boot.starter.websocket)
    implementation(libs.grpc.netty)
    implementation(libs.grpc.client.spring.boot.starter)
    implementation(libs.micrometer.core)
}