plugins {
    id 'crypto-domain'
}

dependencies {
    implementation project(':common:common-web')
    implementation project(':common:common-grpc')
    implementation project(':protobuf')
    implementation project(':market:market-application')

    implementation(libs.spring.cloud.starter.stream.kafka)

    testImplementation project(':common:common-test')
}
