plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-oauth2-authorization-server"

dependencies {
    implementation project(':oauth2-authorization-server:oauth2-authorization-server-application')
    implementation project(':oauth2-authorization-server:oauth2-authorization-server-adapter-in')
    implementation project(':oauth2-authorization-server:oauth2-authorization-server-adapter-out')

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)

    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.micrometer.registry.prometheus)

    testImplementation(libs.spring.security.test)
}