plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-id')
    implementation project(':common:common-web')
    implementation project(':common:common-redis')
    implementation project(':common:common-mongo')
    implementation project(':chat:chat-application')

    implementation(libs.spring.boot.starter.aop)
    implementation(libs.spring.integration.core)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.caffeine)

    testImplementation project(':common:common-test')
}