plugins {
    id 'crypto-common-library'
}


dependencies {

    implementation project(':common')
    implementation project(':chat:chat-contract')
    implementation project(':chat:chat-client')
    implementation project(':chat:chat-domain')
    implementation project(':chat:chat-application')
    implementation project(':chat:chat-adapter-in')
    implementation project(':chat:chat-adapter-out')
    implementation project(':chat:chat-bootstrap')

    implementation(libs.caffeine)

    implementation(platform(libs.grpc.bom))
    implementation(libs.grpc.netty)
    implementation(libs.grpc.protobuf)
    implementation(libs.grpc.stub)
    implementation(libs.grpc.server.spring.boot.starter)
    implementation(libs.protobuf.java)
    implementation(libs.protobuf.util)
    implementation project(':protobuf')

    implementation(libs.spring.integration.core)
    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.spring.boot.starter.aop)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.starter.data.redis)
    implementation(libs.redisson.spring.boot.starter)
    implementation(libs.spring.boot.starter.data.mongodb)
    implementation(libs.spring.cloud.starter.stream.kafka)
    implementation(libs.spring.cloud.stream.binder.kafka)
    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)

    testImplementation project(':common:common-test')
}
