plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-outbox-poller"

dependencies {
    implementation project(':common:common-core')
    implementation project(':common:common-outbox')

    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.cloud.starter.stream.kafka)
    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.starter.bus.kafka)
    implementation(libs.micrometer.registry.prometheus)
    implementation(libs.ulid.creator)

    testImplementation project(':common:common-test')
}