plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-core')
    implementation project(':common:common-redis')
    implementation project(':user:user-client')
    implementation project(':oauth2-authorization-server:oauth2-authorization-server-application')

    implementation platform(libs.grpc.bom)
    implementation(libs.grpc.stub)
    implementation(libs.grpc.client.spring.boot.starter)
    implementation(libs.spring.security.oauth2.authorization.server)
    implementation(libs.micrometer.registry.prometheus)
    implementation(libs.caffeine)
    implementation(libs.protobuf.java)

    testImplementation(libs.spring.security.test)
    testImplementation project(':common:common-test')
}