plugins {
    id 'crypto-common-library'
}

dependencies {
    api project(':common:common-core')

    implementation(libs.spring.boot.starter.data.redis)
    implementation(libs.spring.boot.starter.aop)
    implementation(libs.redisson.spring.boot.starter)

    testImplementation project(':common:common-test')
}