plugins {
    id 'crypto-common-library'
}

dependencies {
    api project(':user:user-contract')

    implementation project(':protobuf')

    implementation platform(libs.grpc.bom)
    implementation(libs.grpc.stub)
    implementation(libs.grpc.client.spring.boot.starter)
    implementation(libs.protobuf.java)
}
