uri:
  public:
    frontend-origin: http://localhost:5173
    api-gateway-origin: https://localhost:8000
  internal:
    config-server: http://crypto-spring-cloud-config:8888
    eureka-server: http://crypto-spring-cloud-eureka-server:8761
    oauth2-authorization-server: http://crypto-oauth2-authorization-server:9000
  discovery:
    user-service: discovery:///user-service
    market-service: discovery:///market-service
    chat-service: discovery:///chat-service
    oauth2-authorization-server: discovery:///oauth2-authorization-server
  provider:
    google:
      issuer: https://accounts.google.com
    kakao:
      issuer: https://kauth.kakao.com
    upbit:
      websocket: wss://api.upbit.com/websocket/v1
