plugins {
    id 'crypto-application'
}

dependencies {
    api project(':common:common-core')
    api project(':common:common-redis')
    api project(':common:common-redisson')
    api project(':chat:chat-domain')
    api project(':chat:chat-contract')

    api(libs.spring.boot.starter.validation)
    api(libs.spring.boot.starter.data.redis)

    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.starter.data.mongodb)
    implementation(libs.spring.cloud.starter.stream.kafka)
    implementation(libs.caffeine)
}