plugins {
    id 'crypto-application'
}

dependencies {
    api project(':chat:chat-domain')

    implementation project(':common:common-core')
    implementation project(':common:common-outbox')
    implementation project(':common:common-redis')
    implementation project(':common:common-redisson')
    implementation project(':chat:chat-contract')

    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.starter.data.mongodb)
    implementation(libs.spring.cloud.stream.binder.kafka)
    implementation(libs.caffeine)
}