plugins {
    id 'crypto-application'
}


dependencies {
    implementation project(':common:common-core')
    implementation project(':common:common-redis')
    implementation project(':chat:chat-domain')
    api project(':chat:chat-contract')

    implementation(libs.spring.boot.starter.validation)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.starter.data.redis)
    implementation(libs.spring.boot.starter.data.mongodb)
    implementation(libs.spring.cloud.starter.stream.kafka)
    implementation(libs.caffeine)

}