services:
  spring-connection-app-0:
    image: spring-connection-app:latest
    container_name: spring-connection-app
    ports:
      - "8100:8100"
    environment:
      - SPRING_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/common?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
#      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
#      - SPRING_DATA_REDIS_HOST=redis
#      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CLOUD_STREAM_INSTANCE_INDEX=0
      - SPRING_CLOUD_STREAM_INSTANCE_COUNT=1
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka-0:9092,kafka-1:9092
      - TESTCONTAINERS_RYUK_DISABLED=true
      - TESTCONTAINERS_CHECKS_DISABLE=true
#    depends_on:
#      - mysql
#      - mongo
#      - redis
#      - kafka-0
#      - kafka-1
    networks:
      - crypto-project-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  crypto-project-network:
    external: true
