plugins {
    id 'crypto-common-library'
}

dependencies {
    api project(':common:common-jpa')
    api project(':common:common-event')
    api project(':common:common-util')

    api 'com.fasterxml.jackson.core:jackson-annotations'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}