syntax = "proto3";

package chatmessage.v1;

option java_package = "org.example.grpc.chatmessage";
option java_multiple_files = true;
option java_outer_classname = "ChatMessageProto";

message GrpcChatMessageRequest {
  string clientMessageId = 1;
  string messageId = 2;
  string roomId = 3;
  string writerId = 4;
  string content = 5;
}

message GrpcChatMessageResponse {
  bool success = 1;
  string id = 2;
  int64 ts = 3;
}

message GrpcChatMessageHardDeleteRequest {
  string messageId = 1;
  string roomId = 2;
  string reason = 3;
}

message GrpcChatMessageHardDeleteResponse {
  bool success = 1;
  string messageId = 2;
  bool deleted = 3;
  bool alreadyDeleted = 4;
  bool notFound = 5;
}

service ChatMessageService {
  rpc save(GrpcChatMessageRequest) returns (GrpcChatMessageResponse);
  rpc HardDelete(GrpcChatMessageHardDeleteRequest) returns (GrpcChatMessageHardDeleteResponse);
}