server.port: 8500

grpc:
  client:
    market-client:
      address: discovery:///market-service
      negotiation-type: plaintext
      max-inbound-message-size:
        bytes: 16777216

spring:
  cloud:
    function:
      definition: upbitTickerEventSupplier;upbitTickerAlertEventConsumer
    stream:
      bindings:
        upbitTickerEventSupplier-out-0:
          destination: upbit-ticker-event
          content-type: application/json
          producer:
            poller:
              fixed-delay:
                nanos: 500_000_000 # 0.5s
        upbitTickerAlertEventConsumer-in-0:
          destination: upbit-ticker-event
          content-type: application/json
          group: upbit-ticker-alert
        price-alert-detected-event-out:
          destination: price-alert-detected-event
          content-type: application/json
          group: upbit-ticker-alert
      kafka:
        binder:
          transaction:
            transaction-id-prefix: tx-market-${app.instance-id}

upbit:
  websocket:
    url: wss://api.upbit.com/websocket/v1
    ticket: test
    ticker-publish-interval: 3s
    ticker-queue-capacity: 100

  ticker:
    alert:
      window-minutes: 3

  store:
    ticker:
      name: upbit-ticker-store
      retention: 3m
      window-size: 3m
      retain-duplicates: false