server.port: 8500

grpc:
  client:
    market-client:
      address: ${uri.discovery.market-service}
      negotiation-type: plaintext
      max-inbound-message-size:
        bytes: 16777216

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    function:
      definition: upbitTickerEventSupplier;upbitTickerAlertEventProcessor
    stream:
      bindings:
        upbitTickerEventSupplier-out-0:
          destination: upbit-ticker-event
          content-type: application/json
          producer:
            use-native-encoding: false
            poller:
              fixed-delay:
                nanos: 500_000_000 # 0.5s
        upbitTickerAlertEventProcessor-in-0:
          destination: upbit-ticker-event
          content-type: application/json
          group: upbit-ticker-alert
        upbitTickerAlertEventProcessor-out-0:
          destination: price-alert-detected-event
          content-type: application/json
      kafka:
        streams:
          binder:
            configuration:
              processing.guarantee: exactly_once_v2

upbit:
  websocket:
    url: ${uri.provider.upbit.websocket}
    ticket: test
    ticker-publish-interval: 10s
    ticker-queue-capacity: 100

  ticker:
    alert:
      window-minutes: 3
      max-event-age: 10s

  store:
    ticker:
      name: upbit-ticker-store
      retention: 3m
      window-size: 3m
      retain-duplicates: false

app:
  grpc:
    market-client:
      deadline: 3500ms
