server:
  port: 8200
  version: v1
  servlet:
    context-path: /api/${server.version}
    encoding:
      charset: UTF-8
      force: true

grpc:
  server:
    port: 18200

spring:
  messages:
    basename: messages,common-validation-messages
    encoding: UTF-8
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  cloud:
    function:
      definition: marketEventConsumer
    stream:
      bindings:
        marketEventConsumer-in-0:
          destination: market-broadcast-event
          contentType: application/json
          group: market-broadcast-${app.instance-id}
      kafka:
        binder:
          consumer-properties:
            spring.json.trusted.packages: "*"
        bindings:
          marketEventConsumer-in-0:
            consumer:
              reset-offsets: false
              start-offset: latest
              ack-mode: record

mysql:
  username: ${mysql.market.username} # user
  password: ${mysql.market.password} # userpass
  db: ${mysql.market.db} # user
api-path:
  market:
    markets: ${api-contract.market.markets}
    price-alerts-me: ${api-contract.market.price-alerts-me}
