server:
  port: 8900
  servlet:
    encoding:
      charset: UTF-8
      force: true

grpc:
  client:
    user-client:
      address: discovery:///user-service
      negotiation-type: plaintext
      max-inbound-message-size:
        bytes: 16777216 # 16MB
    oauth2-authorization-server-client:
      address: discovery:///oauth2-authorization-server
      negotiation-type: plaintext
      max-inbound-message-size:
        bytes: 16777216 # 16MB
  server.enabled: false

api-path:
  auth:
    pattern: /auth/**
    logout: /auth/logout
    refresh: /auth/refresh
  oauth2:
    authorization-base-uri: /oauth2/authorization
    authorization-pattern: /oauth2/**
    login-callback-pattern: /login/oauth2/code/**
    login-callback-base-uri: /login/oauth2/code/*

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: https://localhost:8000/login/oauth2/code/google
          kakao:
            provider: kakao
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile_nickname
              - account_email
            redirect-uri: https://localhost:8000/login/oauth2/code/kakao # TODO: 주입하기 (authorization server -> client의 redirect request param으로 사용)
          my-authorization-server:
            provider: my-authorization-server
            client-id: ${my.client-id}
            client-secret: ${my.client-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange # refresh-token
            redirect-uri: http://crypto-oauth2-authorization-server:9000/not/use
        provider:
          google:
            issuer-uri: https://accounts.google.com
            user-name-attribute: email # nameAttributeKey 필드에 대입
          kakao:
            issuer-uri: https://kauth.kakao.com
            user-name-attribute: email # nameAttributeKey 필드에 대입
          my-authorization-server:
            authorization-uri: http://crypto-oauth2-authorization-server:9000/oauth2/authorize # 인가 코드 요청
            token-uri: http://crypto-oauth2-authorization-server:9000/oauth2/token

oauth2:
  internal-auth-server:
    client-registration-id: my-authorization-server
