server:
  port: 8900
  servlet:
    encoding:
      charset: UTF-8
      force: true

grpc:
  client:
    user-client:
      address: ${uri.discovery.user-service}
      negotiation-type: plaintext
      max-inbound-message-size:
        bytes: 16777216 # 16MB
    oauth2-authorization-server-client:
      address: ${uri.discovery.oauth2-authorization-server}
      negotiation-type: plaintext
      max-inbound-message-size:
        bytes: 16777216 # 16MB
  server.enabled: false

api-path:
  auth:
    pattern: ${api-contract.auth.pattern}
    logout: ${api-contract.auth.logout}
    refresh: ${api-contract.auth.refresh}
  oauth2:
    authorization-base-uri: ${api-contract.oauth2.authorization-base}
    authorization-pattern: ${api-contract.oauth2.pattern}
    login-callback-pattern: ${api-contract.oauth2.login-callback-pattern}
    login-callback-base-uri: ${api-contract.oauth2.login-callback-base-uri}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: ${uri.public.api-gateway-origin}${api-contract.oauth2.login-callback-base}/google
          kakao:
            provider: kakao
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile_nickname
              - account_email
            redirect-uri: ${uri.public.api-gateway-origin}${api-contract.oauth2.login-callback-base}/kakao
          my-authorization-server:
            provider: my-authorization-server
            client-id: ${my.client-id}
            client-secret: ${my.client-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange # refresh-token
            redirect-uri: ${uri.internal.oauth2-authorization-server}/not/use
        provider:
          google:
            issuer-uri: ${uri.provider.google.issuer}
            user-name-attribute: email # nameAttributeKey 필드에 대입
          kakao:
            issuer-uri: ${uri.provider.kakao.issuer}
            user-name-attribute: email # nameAttributeKey 필드에 대입
          my-authorization-server:
            authorization-uri: ${uri.internal.oauth2-authorization-server}/oauth2/authorize # 인가 코드 요청
            token-uri: ${uri.internal.oauth2-authorization-server}/oauth2/token

oauth2:
  internal-auth-server:
    client-registration-id: my-authorization-server
