server:
  port: 8090
  version: v1
  servlet:
    context-path: /api/${server.version}
    encoding:
      charset: UTF-8
      force: true

grpc:
  server:
    port: 18090

api-path:
  user:
    base: ${api-contract.user.base}
    sign-up: ${api-contract.user.sign-up}
    me: ${api-contract.user.me}
    profile: ${api-contract.user.profile}

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

mysql:
  username: ${mysql.user.username} # user
  password: ${mysql.user.password} # userpass
  db: ${mysql.user.db} # user

#logging:
#  level:
#    org.springframework.security: debug
