server:
  port: 8100

grpc:
  client:
    chat-client:
      address: ${uri.discovery.chat-service}
      negotiation-type: plaintext
      max-inbound-message-size:
        bytes: 16777216 # 16MB
#      enable-keep-alive: true
#      keep-alive-time:
#        seconds: 30
  server:
    enabled: false

api-path:
  websocket:
    sock-js-endpoint: ${api-contract.websocket.sock-js-endpoint}
    native-endpoint: ${api-contract.websocket.native-endpoint}
  stomp:
    application-destination-prefix: ${api-contract.websocket.application-destination-prefix}
    user-destination-prefix: ${api-contract.websocket.user-destination-prefix}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    function:
      definition: myChatRoomBadgeEventConsumer;chatMessageBroadcastEventConsumer;webNotificationEventConsumer
    stream:
      bindings:
        myChatRoomBadgeEventConsumer-in-0:
          destination: chatroom-broadcast-event
          contentType: application/json
          group: chatroom-broadcast-event-${app.instance-id}
          consumer:
            concurrency: 2
        chatMessageBroadcastEventConsumer-in-0:
          destination: chatmessage-broadcast-event
          contentType: application/json
          group: chatmessage-broadcast-${app.instance-id}
          consumer:
            concurrency: 2
        webNotificationEventConsumer-in-0:
          destination: web-notification-broadcast-event
          contentType: application/json
          group: web-notification-broadcast-${app.instance-id}
          consumer:
            concurrency: 2
      kafka:
        binder:
          consumer-properties:
            spring.json.trusted.packages: "*"
        bindings:
          myChatRoomBadgeEventConsumer-in-0:
            consumer:
              reset-offsets: false
              start-offset: latest
              ack-mode: record
          chatMessageBroadcastEventConsumer-in-0:
            consumer:
              reset-offsets: false
              start-offset: latest
              ack-mode: record
          webNotificationEventConsumer-in-0:
            consumer:
              reset-offsets: false
              start-offset: latest
              ack-mode: record

websocket:
  session:
    # STOMP 세션 위치 Redis TTL(연결 유휴 만료. subscribe 마다 갱신)
    ttl: 3m
