plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-core')
    implementation project(':common:common-web')
    implementation project(':common:common-grpc')
    implementation project(':oauth2-authorization-server:oauth2-authorization-server-application')
    implementation project(':protobuf')

    implementation(libs.grpc.server.spring.boot.starter)
    implementation(libs.protobuf.java)

    implementation(libs.spring.security.oauth2.authorization.server)

    testImplementation project(':common:common-test')
    testImplementation project(':common:common-redis')
    testImplementation project(':oauth2-authorization-server:oauth2-authorization-server-adapter-out')
    testImplementation(libs.spring.security.test)
    testImplementation(libs.spring.boot.starter.data.redis)
    testImplementation(libs.caffeine)
}