plugins {
    id 'crypto-adapter'
}

dependencies {
    api project(':common:common-core')
    api project(':common:common-web')
    api project(':common:common-grpc')
    api project(':oauth2-authorization-server:oauth2-authorization-server-application')
    api project(':protobuf')

    api platform(libs.grpc.bom)
    api(libs.grpc.stub)
    api(libs.grpc.server.spring.boot.starter)
    api(libs.protobuf.java)

    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.security.oauth2.authorization.server)

    testImplementation project(':oauth2-authorization-server:oauth2-authorization-server-adapter-out')
    testImplementation project(':common:common-test')
    testImplementation project(':common:common-redis')
    testImplementation(libs.spring.security.test)
    testImplementation(libs.spring.boot.starter.data.redis)
    testImplementation(libs.caffeine)
}