plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-market-detection"

dependencies {
    implementation project(':common:common-actuator-webmvc')
    implementation project(':common:common-time')
    implementation project(':common:common-exception')
    implementation project(':common:common-validation')
    implementation project(':common:common-event')
    implementation project(':upbit-connector:upbit-connector-contract')
    implementation project(':market-detection:market-detection-application')
    implementation project(':market-detection:market-detection-adapter-in')
    implementation project(':market-detection:market-detection-contract')
    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)
    implementation(libs.spring.cloud.stream.binder.kafka.streams)
    implementation(libs.spring.cloud.starter.bus.kafka)
    implementation(libs.micrometer.registry.prometheus)

    testImplementation project(':common:common-test')
    testImplementation(libs.kafka.streams.test.utils)
}
