plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-market-detection"

dependencies {
    implementation project(':common:common-event')
    implementation project(':market:market-client')
    implementation project(':market-detection:market-detection-contract')

    implementation(libs.okhttp)
    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)
    implementation(libs.spring.cloud.stream.binder.kafka.streams)
    implementation(libs.spring.cloud.starter.bus.kafka)

    testImplementation project(':common:common-test')
    testImplementation(libs.kafka.streams.test.utils)
}
