plugins {
    id 'crypto-application'
}


dependencies {
    implementation project(':common:common-core')
    implementation project(':websocket-gateway:websocket-gateway-domain')
    implementation project(':protobuf')

    implementation platform(libs.grpc.bom)
    implementation(libs.grpc.stub)
    implementation(libs.spring.boot.starter.websocket)
    implementation(libs.caffeine)

}