plugins {
    id 'crypto-application'
}

dependencies {
    api project(':user:user-domain')

    implementation project(':common:common-exception')
    implementation project(':common:common-validation')
    implementation project(':common:common-jpa')
    implementation(libs.spring.security.crypto)
}
