plugins {
    id 'crypto-bootstrap'
}

configurations {
    otelAgent
}

tasks.register('copyOtelAgent', Copy) {
    from configurations.otelAgent
    into "${layout.buildDirectory}/otel"
    rename { "opentelemetry-javaagent.jar" }
}

dependencies {
    implementation project(':websocket-gateway:websocket-gateway-domain')
    implementation project(':websocket-gateway:websocket-gateway-application')
    implementation project(':websocket-gateway:websocket-gateway-adapter-in')
    implementation project(':websocket-gateway:websocket-gateway-adapter-out')

    otelAgent(libs.otel.javaagent)

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)

    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.micrometer.registry.prometheus)
}