plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-websocket-gateway"

configurations {
    otelAgent
}

tasks.register('copyOtelAgent', Copy) {
    from configurations.otelAgent
    into "${layout.buildDirectory}/otel"
    rename { "opentelemetry-javaagent.jar" }
}

dependencies {
    implementation project(':common:common-actuator-webmvc')
    implementation project(':websocket-gateway:websocket-gateway-adapter-in')
    implementation project(':websocket-gateway:websocket-gateway-adapter-out')
    implementation project(':websocket-gateway:websocket-gateway-application')

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)
    implementation(libs.micrometer.registry.prometheus)

    otelAgent(libs.otel.javaagent)
}