plugins {
    id 'crypto-bootstrap'
}


dependencies {

    implementation project(':common')
    implementation project(':common:common-event')
    implementation(libs.okhttp)

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)
    implementation(libs.spring.cloud.starter.stream.kafka)
    implementation(libs.spring.cloud.stream.binder.kafka)
    implementation(libs.spring.cloud.stream.binder.kafka.streams)

    testImplementation(libs.kafka.streams.test.utils)
}
