plugins {
    id 'crypto-bootstrap'
}

dependencies {
    implementation project(':common')
    implementation project(':common:common-event')

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)

    testImplementation project(':common:common-test')
}
