plugins {
    id 'crypto-bootstrap'
}

dependencies {
    implementation project(':user:user-domain')
    implementation project(':user:user-application')
    implementation project(':user:user-adapter-in')
    implementation project(':user:user-adapter-out')

    runtimeOnly(libs.mysql.connector.j) {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
    }

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)

    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.micrometer.registry.prometheus)
}