plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-id')
    implementation project(':common:common-jpa')
    implementation project(':user:user-application')

    implementation(libs.spring.security.crypto)

    testImplementation project(':common:common-test')
}