plugins {
    id 'crypto-common-library'
}

dependencies {
    api project(':common:common-core')
    api project(':common:common-exception')
    api project(':common:common-validation')
    api project(':common:common-time')
    api project(':common:common-jpa')
    api project(':common:common-event')
    api project(':common:common-web')
    api project(':common:common-grpc')
    api project(':common:common-id')
    api project(':common:common-inbox')
    api project(':common:common-outbox')
    api project(':common:common-redis')
    api project(':common:common-redisson')
    api project(':common:common-util')
    api project(':common:common-tx')
    api project(':common:common-mongo')
}
