syntax = "proto3";

package auth.v1;

option java_package = "org.example.grpc.auth";
option java_multiple_files = true;
option java_outer_classname = "AuthProto";

import "google/protobuf/wrappers.proto"; // StringValue, BoolValue

message GrpcFindAccessTokenRequest {
  string clientRegistrationId = 1;
  string username = 2;
}

message GrpcFindRefreshTokenRequest {
  string clientRegistrationId = 1;
  string username = 2;
}

message GrpcRegisterBlacklistTokenRequest {
  string accessToken = 1;
}

message GrpcExistsBlacklistTokenRequest {
  string accessToken = 1;
}

message SaveAuthorizedClientRequest {
  string clientRegistrationId   = 1;
  string email                  = 2;
  map<string,string> claims = 3;
  string accessToken            = 4;
  string refreshToken           = 5;
}

message RemoveAuthorizedClientRequest {
  string email                  = 1;
}

service AccessTokenService {
  rpc findValue(GrpcFindAccessTokenRequest) returns (google.protobuf.StringValue);
}

service RefreshTokenService {
  rpc findValue(GrpcFindRefreshTokenRequest) returns (google.protobuf.StringValue);
}

service BlacklistTokenService {
  rpc register(GrpcRegisterBlacklistTokenRequest) returns (google.protobuf.BoolValue);
  rpc exists(GrpcExistsBlacklistTokenRequest) returns (google.protobuf.BoolValue);
}

service AuthorizedClientService {
  rpc save(SaveAuthorizedClientRequest) returns (google.protobuf.BoolValue);
  rpc remove(RemoveAuthorizedClientRequest) returns (google.protobuf.BoolValue);
}
