plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-notification-service"

dependencies {
    implementation project(':common:common-actuator-webmvc')
    implementation project(':notification:notification-domain')
    implementation project(':notification:notification-application')
    implementation project(':notification:notification-adapter-in')
    implementation project(':notification:notification-adapter-out')

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)
    implementation(libs.spring.cloud.starter.bus.kafka)
    implementation(libs.micrometer.registry.prometheus)
}