plugins {
    id 'crypto-adapter'
}


dependencies {
    api project(':common:common-core')
    api project(':common:common-web')
    api project(':common:common-grpc')
    api project(':user:user-application')
    api project(':protobuf')

    api platform(libs.grpc.bom)
    api libs.grpc.stub
    api libs.grpc.server.spring.boot.starter
    api libs.spring.boot.starter.web
    api libs.spring.boot.starter.security
    implementation libs.protobuf.java
    implementation libs.protobuf.util

}
