plugins {
    id 'crypto-bootstrap'
}

ext.dockerImageName = "crypto-market-service"

dependencies {
    implementation project(':common:common-actuator-webmvc')
    implementation project(':market:market-domain')
    implementation project(':market:market-application')
    implementation project(':market:market-adapter-in')
    implementation project(':market:market-adapter-out')

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)
    implementation(libs.spring.cloud.starter.bus.kafka)
    implementation(libs.micrometer.registry.prometheus)
}