plugins {
    id 'crypto-adapter'
}


dependencies {
    api project(':common:common-core')
    implementation project(':common:common-web')
    implementation project(':spring-cloud-api-gateway:spring-cloud-api-gateway-application')

    implementation(libs.spring.boot.starter.webflux)
    implementation(libs.spring.boot.starter.security)
    implementation(libs.spring.security.oauth2.jose)
    implementation(libs.spring.security.oauth2.resource.server)
    implementation(libs.spring.cloud.gateway)
    implementation(libs.spring.cloud.loadbalancer)
    implementation platform(libs.grpc.bom)
    implementation(libs.grpc.netty)

    testImplementation project(':spring-cloud-api-gateway:spring-cloud-api-gateway-adapter-out')
    testImplementation project(':protobuf')
    testImplementation(libs.spring.security.test)
    testImplementation(libs.reactor.test)
    testImplementation project(':common:common-test')
}