plugins {
    id 'crypto-bootstrap'
}

dependencies {
    implementation project(':oauth2-client:oauth2-client-application')
    implementation project(':oauth2-client:oauth2-client-adapter-in')
    implementation project(':oauth2-client:oauth2-client-adapter-out')

    implementation(libs.spring.cloud.config.client)
    implementation(libs.spring.cloud.eureka.client)

    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.micrometer.registry.prometheus)

    testImplementation(libs.spring.security.test)
}
