plugins {
    id 'crypto-application'
}

dependencies {
    api project(':common:common-core')
    api project(':user:user-contract')

    api(libs.spring.security.oauth2.authorization.server)

    implementation(libs.spring.boot.starter.web)

    testImplementation project(':common:common-test')
    testImplementation(libs.spring.security.test)
}