plugins {
    id 'crypto-common-library'
}

dependencies {
    api project(':common:common-jpa')
    api(libs.spring.messaging)

    implementation project(':common:common-core')
    implementation project(':common:common-util')

    testImplementation project(':common:common-outbox')
    testImplementation project(':common:common-test')
}
