plugins {
    id 'crypto-common-library'
}

dependencies {
    api project(':common:common-jpa')
    api(libs.spring.messaging)

    implementation project(':common:common-core')
    implementation project(':common:common-util')
    implementation(libs.jackson.annotations)

    testImplementation(libs.jackson.databind)
}
