eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}:${app.instance-id}
    metadata-map:
      gRPC_port: ${grpc.server.port}
      gRPC_service_config: '{"loadBalancingConfig":[{"round_robin":{}}]}'

  client:
    serviceUrl:
      defaultZone: http://crypto-spring-cloud-eureka-server:8761/eureka/
    healthCheck:
      enabled: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10