spring:
  datasource:
    write:
      url: ${uri.datastore.mysql.write}
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: ${mysql.write.pool.max-size:10}
        minimum-idle: ${mysql.write.pool.min-idle:2}
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: ${mysql.write.pool.connection-timeout:30000}
        pool-name: write-pool
    read:
      url: ${uri.datastore.mysql.read}
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: read-pool
