plugins {
    id 'crypto-adapter'
}

dependencies {
    implementation project(':common:common-event')
    implementation project(':market:market-client')
    implementation project(':upbit-connector:upbit-connector-application')

    implementation(libs.spring.boot.starter.webflux)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.micrometer.core)

    testImplementation(libs.reactor.test)
}
